"""
GA Generation Loop — Automated A3→A6 pipeline

Implements the channel-delta convergence loop from docs/ga_generation/05_ALGORITHM.md:
  A3: Ask Gemini for ideal channel spec per claim
  A4: Compare ideal channels vs current parametric SVG → compute delta
  A5: Generate layout fixes to close top-N delta channels
  A6: Apply fixes to YAML, compile, validate via reader sim

Usage:
  python iterate_ga.py [--version 18] [--max-iters 5] [--target 0.50]
"""

import yaml
import json
import os
import sys
import copy
import argparse
import subprocess
import time

# Add scisense root
_ROOT = os.path.normpath(os.path.join(os.path.dirname(__file__), "..", "..", ".."))
if _ROOT not in sys.path:
    sys.path.insert(0, _ROOT)

BASE = os.path.normpath(os.path.join(os.path.dirname(__file__), ".."))
CONFIG_DIR = os.path.join(BASE, "config")
SCRIPTS_DIR = os.path.join(BASE, "scripts")
ARTEFACTS_DIR = os.path.join(BASE, "artefacts")
DELTA_DIR = os.path.join(ARTEFACTS_DIR, "channel_deltas")
os.makedirs(DELTA_DIR, exist_ok=True)

# Gemini setup
import google.generativeai as genai

def load_gemini_key():
    env_path = os.path.join(_ROOT, "glance", ".env")
    if os.path.exists(env_path):
        with open(env_path) as f:
            for line in f:
                if line.startswith("GEMINI_API_KEY="):
                    return line.strip().split("=", 1)[1]
    return os.environ.get("GEMINI_API_KEY", "")


def load_claims_spec():
    path = os.path.join(CONFIG_DIR, "claims_spec.yaml")
    with open(path, "r", encoding="utf-8") as f:
        return yaml.safe_load(f)


def load_layout(version):
    path = os.path.join(CONFIG_DIR, f"layout_v{version}.yaml")
    with open(path, "r", encoding="utf-8") as f:
        return yaml.safe_load(f)


def save_layout(layout, version):
    path = os.path.join(CONFIG_DIR, f"layout_v{version}.yaml")
    # Add header comment
    header = (
        f"# Layout V{version} — Auto-generated by iterate_ga.py (channel-delta loop)\n"
        f"# Generated from V{version-1} + Gemini-guided channel fixes\n"
        f"# All positions in fractions of canvas (0.0-1.0)\n\n"
    )
    with open(path, "w", encoding="utf-8") as f:
        f.write(header)
        yaml.dump(layout, f, default_flow_style=False, allow_unicode=True, sort_keys=False)
    print(f"  Saved layout_v{version}.yaml")


# ════════════════════════════════════════════════════════════
# A3: AI Reference — ask Gemini for ideal channel assignments
# ════════════════════════════════════════════════════════════

def _get_modifiable_params(layout):
    """Extract all modifiable numeric params from layout as dotted paths."""
    params = {}

    def _walk(obj, prefix=""):
        if isinstance(obj, dict):
            for k, v in obj.items():
                path = f"{prefix}.{k}" if prefix else k
                if isinstance(v, (int, float)):
                    params[path] = v
                elif isinstance(v, dict):
                    _walk(v, path)
                elif isinstance(v, list) and all(isinstance(x, dict) for x in v):
                    for i, item in enumerate(v):
                        _walk(item, f"{path}[{i}]")

    _walk(layout)
    return params


def a3_gemini_ideal(claims_spec, current_layout, model, version=18):
    """Ask Gemini Vision to analyze current GA and suggest param changes."""
    import PIL.Image

    # Load current GA image
    img_path = os.path.join(ARTEFACTS_DIR, "wireframes", f"wireframe_GA_v{version}_full.png")
    if not os.path.exists(img_path):
        print(f"  Warning: No image at {img_path}, falling back to text-only")
        return {"channel_delta": {"fixes": [], "layout_adjustments": []}}

    img = PIL.Image.open(img_path)

    # Build claim descriptions
    claims_text = ""
    for cid, claim in claims_spec.get("claims", {}).items():
        if claim.get("priority", 3) <= 2:
            claims_text += f"- {cid} (P{claim['priority']}): {claim['text']}\n"

    # Get all modifiable params
    params = _get_modifiable_params(current_layout)
    # Filter to layout-relevant params (panels, bronchus, evidence, vicious_cycle, etc)
    relevant_prefixes = [
        "panels.", "bronchus.", "evidence.", "vicious_cycle.",
        "child_sick.", "child_healthy.", "central_arrow.",
        "zone_orientation.", "bottom_panel.",
    ]
    relevant_params = {
        k: v for k, v in params.items()
        if any(k.startswith(p) for p in relevant_prefixes)
    }
    params_text = "\n".join(f"  {k}: {v}" for k, v in sorted(relevant_params.items()))

    prompt = f"""Look at this scientific Graphical Abstract. It shows immunomodulators
for pediatric respiratory infections.

PROBLEM: The evidence section (middle panel with bars) gets only ~35% reader attention.
The bronchus diagram (top) dominates. Target: evidence > 50%.

Under-encoded claims:
- c13 (P1): "These agents break the link between early viral infections and asthma"
  MISSING: color_gradient (red→green background), spatial_sequence (vicious cycle too small)
- c14 (P1): "These agents fill a therapeutic gap in children aged 0-5"
  MISSING: spatial_frame (no explicit framing of the problem→solution)

MODIFIABLE PARAMETERS (current values):
{params_text}

RULES:
1. ONLY suggest changes to parameters listed above
2. Values must be numeric (float or int)
3. Maximum 8 changes per iteration
4. Focus on the biggest visual impact changes first

Output ONLY valid YAML:
layout_adjustments:
  - param: "exact.dotted.path"
    current: 0.42
    proposed: 0.35
    reason: "short reason"
"""

    response = model.generate_content([prompt, img])
    text = response.text

    # Extract YAML
    if "```yaml" in text:
        text = text.split("```yaml")[1].split("```")[0]
    elif "```" in text:
        text = text.split("```")[1].split("```")[0]

    try:
        result = yaml.safe_load(text)
    except Exception as e:
        print(f"  Warning: Could not parse Gemini response: {e}")
        print(f"  Raw:\n{text[:500]}")
        result = {"layout_adjustments": []}

    # Validate: only allow changes to known params
    validated = []
    for adj in result.get("layout_adjustments", []):
        param = adj.get("param", "")
        proposed = adj.get("proposed")
        if param in relevant_params and isinstance(proposed, (int, float)):
            validated.append(adj)
        else:
            print(f"  Rejected: {param} (not in known params or not numeric)")

    result["layout_adjustments"] = validated
    result["fixes"] = []  # No free-form fixes
    return {"channel_delta": result}


# ════════════════════════════════════════════════════════════
# A4: Channel Delta — compare ideal vs current
# ════════════════════════════════════════════════════════════

def a4_compute_delta(claims_spec, current_layout):
    """Compute channel delta: which channels are below minimum for P1 claims."""

    ev = current_layout.get("evidence", {})
    items = ev.get("items", [])

    # Detect renderer-level features (not per-item, but global)
    global_channels = set()

    # Background gradient (c13 color_gradient)
    bg_grad = current_layout.get("background_gradient", {})
    if bg_grad.get("enabled", False):
        global_channels.add("color_gradient")

    # Vicious cycle (c13 spatial_sequence, shape)
    vc = current_layout.get("vicious_cycle", {})
    if vc.get("radius_x", 0) > 0:
        global_channels.add("spatial_sequence")
        global_channels.add("shape")

    # Children silhouettes (c13 position_x, icon)
    if current_layout.get("child_sick", {}).get("x_pct") is not None:
        global_channels.add("position_x")
    if current_layout.get("child_sick", {}).get("scale", 0) > 0:
        global_channels.add("icon")

    # Central arrow (c14 spatial_frame)
    ca = current_layout.get("central_arrow", {})
    if ca.get("enabled", False) and ca.get("opacity", 0) > 0.1:
        global_channels.add("spatial_frame")

    # Zone orientation labels
    zo = current_layout.get("zone_orientation", {})
    if zo.get("pathological") and zo.get("protected"):
        global_channels.add("text_label")

    deltas = []

    for cid, claim in claims_spec.get("claims", {}).items():
        if claim.get("priority", 3) > 1:
            continue  # Only P1 claims

        min_ch = claim.get("min_channels", 3)
        spec_channels = {ch["channel"] for ch in claim.get("channels", [])}

        # Count implemented channels — start with global channels
        implemented = set(global_channels)

        # Add evidence-section channels
        for item in items:
            if item.get("width_pct", 0) > 0:
                implemented.add("length")
            implemented.add("position_y")
            implemented.add("color_value")
            if ev.get("rct_circles", {}).get("enabled"):
                implemented.add("size")
            if ev.get("outcome_badges", {}).get("enabled"):
                if item.get("outcomes"):
                    implemented.add("icon")
                    implemented.add("color_hue")
            if ev.get("number_callouts", {}).get("enabled"):
                if item.get("number_callout"):
                    implemented.add("number")
            implemented.add("text_label")

        missing = spec_channels - implemented
        coverage = len(implemented & spec_channels) / max(len(spec_channels), 1)

        deltas.append({
            "claim_id": cid,
            "claim_text": claim["text"],
            "priority": claim["priority"],
            "min_channels": min_ch,
            "spec_channels": sorted(spec_channels),
            "implemented": sorted(implemented & spec_channels),
            "missing": sorted(missing),
            "coverage": round(coverage, 2),
            "below_min": len(implemented & spec_channels) < min_ch,
        })

    return sorted(deltas, key=lambda d: d["coverage"])


# ════════════════════════════════════════════════════════════
# A5: Apply Fixes — modify layout YAML
# ════════════════════════════════════════════════════════════

def a5_apply_fixes(layout, gemini_result):
    """Apply ONLY validated layout adjustments to existing params."""

    new_layout = copy.deepcopy(layout)
    applied = []

    delta = gemini_result.get("channel_delta", gemini_result)

    # Apply layout adjustments (panel sizes, positions) — ONLY numeric, ONLY existing keys
    for adj in delta.get("layout_adjustments", []):
        param = adj.get("param", "")
        value = adj.get("proposed")
        if not param or not isinstance(value, (int, float)):
            continue

        # Navigate dotted path — reject if path doesn't exist
        parts = param.split(".")
        target = new_layout
        valid = True
        for p in parts[:-1]:
            if isinstance(target, dict) and p in target:
                target = target[p]
            else:
                valid = False
                break

        if valid and isinstance(target, dict) and parts[-1] in target:
            old = target[parts[-1]]
            if isinstance(old, (int, float)):
                target[parts[-1]] = value
                applied.append(f"{param}: {old} → {value} ({adj.get('reason', '')})")
            else:
                print(f"  Skipped {param}: existing value {old} is not numeric")

    return new_layout, applied


# ════════════════════════════════════════════════════════════
# A6: Compile + Validate
# ════════════════════════════════════════════════════════════

def a6_compile(version):
    """Create compose script for new version and compile."""

    src_script = os.path.join(SCRIPTS_DIR, f"compose_ga_v{version-1}.py")
    dst_script = os.path.join(SCRIPTS_DIR, f"compose_ga_v{version}.py")

    if not os.path.exists(src_script):
        # Try to find the latest existing script
        for v in range(version-1, 9, -1):
            candidate = os.path.join(SCRIPTS_DIR, f"compose_ga_v{v}.py")
            if os.path.exists(candidate):
                src_script = candidate
                break

    # Always regenerate from source to ensure correct references
    with open(src_script, "r", encoding="utf-8") as f:
        code = f.read()

    # Find what version the source script targets (could be any previous version)
    import re
    layout_match = re.search(r'layout_v(\d+)\.yaml', code)
    src_v = int(layout_match.group(1)) if layout_match else version - 1

    # Update layout reference
    code = code.replace(f"layout_v{src_v}.yaml", f"layout_v{version}.yaml")

    # Update output filenames
    code = code.replace(f"wireframe_GA_v{src_v}", f"wireframe_GA_v{version}")

    # Update version prints
    code = code.replace(f"V{src_v} compilation", f"V{version} compilation")

    with open(dst_script, "w", encoding="utf-8") as f:
        f.write(code)
    print(f"  Created compose_ga_v{version}.py (from v{src_v} source)")

    # Compile
    print(f"  Compiling V{version}...")
    result = subprocess.run(
        [sys.executable, dst_script],
        capture_output=True, text=True, timeout=120
    )

    if result.returncode != 0:
        print(f"  COMPILE ERROR:\n{result.stderr[:500]}")
        return False

    print(f"  V{version} compiled successfully")
    return True


# ════════════════════════════════════════════════════════════
# MAIN LOOP
# ════════════════════════════════════════════════════════════

def iterate(start_version=18, max_iters=3, target_coverage=0.50):
    """Run the channel-delta convergence loop."""

    print(f"\n{'='*60}")
    print(f"GA Generation Loop — Starting from V{start_version}")
    print(f"Target: evidence coverage > {target_coverage*100:.0f}%")
    print(f"Max iterations: {max_iters}")
    print(f"{'='*60}\n")

    # Load claims spec (constant across iterations)
    claims_spec = load_claims_spec()

    # Setup Gemini
    api_key = load_gemini_key()
    if not api_key:
        print("ERROR: No GEMINI_API_KEY found")
        return
    genai.configure(api_key=api_key)
    model = genai.GenerativeModel("gemini-2.5-flash")

    version = start_version

    for i in range(max_iters):
        print(f"\n--- Iteration {i+1}/{max_iters} (V{version} → V{version+1}) ---\n")

        # Load current layout
        layout = load_layout(version)

        # A4: Compute channel delta
        print("A4: Computing channel delta...")
        deltas = a4_compute_delta(claims_spec, layout)

        min_coverage = min(d["coverage"] for d in deltas) if deltas else 0
        avg_coverage = sum(d["coverage"] for d in deltas) / len(deltas) if deltas else 0

        print(f"  P1 claim coverage: min={min_coverage:.0%}, avg={avg_coverage:.0%}")
        for d in deltas:
            status = "BELOW MIN" if d["below_min"] else "OK"
            missing_str = ", ".join(d["missing"]) if d["missing"] else "none"
            print(f"  {d['claim_id']}: {d['coverage']:.0%} [{status}] missing: {missing_str}")

        if avg_coverage >= target_coverage and not any(d["below_min"] for d in deltas):
            print(f"\n  Target reached! Avg coverage {avg_coverage:.0%} >= {target_coverage:.0%}")
            break

        # A3: Ask Gemini for ideal
        print("\nA3: Querying Gemini for ideal channel assignments...")
        gemini_result = a3_gemini_ideal(claims_spec, layout, model, version=version)

        # Save Gemini response
        delta_path = os.path.join(DELTA_DIR, f"delta_v{version}_to_v{version+1}.yaml")
        with open(delta_path, "w", encoding="utf-8") as f:
            yaml.dump(gemini_result, f, default_flow_style=False, allow_unicode=True)
        print(f"  Saved delta analysis to {delta_path}")

        # A5: Apply fixes
        print("\nA5: Applying Gemini fixes...")
        new_layout, applied = a5_apply_fixes(layout, gemini_result)

        if not applied:
            print("  No applicable fixes found. Trying manual fallbacks...")
            # Fallback: reduce bronchus, increase evidence
            panels = new_layout.get("panels", {})
            top = panels.get("top", {})
            ev_panel = panels.get("evidence", {})
            if top.get("height_pct", 0.42) > 0.30:
                old_top = top["height_pct"]
                top["height_pct"] = round(old_top - 0.05, 2)
                ev_panel["height_pct"] = round(ev_panel.get("height_pct", 0.25) + 0.05, 2)
                ev_panel["y_pct"] = round(top["height_pct"] + 0.01, 2)
                applied.append(f"top panel: {old_top} → {top['height_pct']} (manual fallback)")

        for a in applied:
            print(f"  Applied: {a}")

        # Save new layout
        version += 1
        save_layout(new_layout, version)

        # A6: Compile
        print(f"\nA6: Compiling V{version}...")
        success = a6_compile(version)

        if not success:
            print(f"  Compilation failed. Stopping at V{version}.")
            break

        print(f"\n  V{version} ready. Check artefacts/wireframes/wireframe_GA_v{version}_full.png")

        # Brief pause between iterations (rate limiting)
        if i < max_iters - 1:
            time.sleep(2)

    print(f"\n{'='*60}")
    print(f"Loop complete. Final version: V{version}")
    print(f"{'='*60}")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="GA Generation Loop")
    parser.add_argument("--version", type=int, default=18, help="Starting version")
    parser.add_argument("--max-iters", type=int, default=3, help="Max iterations")
    parser.add_argument("--target", type=float, default=0.50, help="Target coverage")
    args = parser.parse_args()

    iterate(args.version, args.max_iters, args.target)
